# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: functions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66unctions.proto\".\n\x1d\x43onstValueFloatFunctionConfig\x12\r\n\x05value\x18\x01 \x01(\x02\"7\n\x19LinearFloatFunctionConfig\x12\r\n\x05start\x18\x01 \x01(\x02\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x02\"R\n\x16SinFloatFunctionConfig\x12\x0b\n\x03min\x18\x01 \x01(\x02\x12\x0b\n\x03max\x18\x02 \x01(\x02\x12\r\n\x05phase\x18\x03 \x01(\x02\x12\x0f\n\x07repeats\x18\x04 \x01(\x02\"^\n\x18StepsFloatFunctionConfig\x12\x11\n\tnum_steps\x18\x01 \x01(\x02\x12\x15\n\rdiff_per_step\x18\x02 \x01(\x02\x12\x18\n\x10\x66irst_step_value\x18\x03 \x01(\x02\"X\n\x19RepeatFloatFunctionConfig\x12\x15\n\rnumberOfTimes\x18\x01 \x01(\x02\x12$\n\x0c\x66uncToRepeat\x18\x02 \x01(\x0b\x32\x0e.FloatFunction\"Q\n\x17HalfFloatFunctionConfig\x12\x1a\n\x02\x66\x31\x18\x01 \x01(\x0b\x32\x0e.FloatFunction\x12\x1a\n\x02\x66\x32\x18\x02 \x01(\x0b\x32\x0e.FloatFunction\"t\n\x18\x43omb2FloatFunctionConfig\x12\x1a\n\x02\x66\x31\x18\x01 \x01(\x0b\x32\x0e.FloatFunction\x12\x0f\n\x07\x61mount1\x18\x02 \x01(\x02\x12\x1a\n\x02\x66\x32\x18\x03 \x01(\x0b\x32\x0e.FloatFunction\x12\x0f\n\x07\x61mount2\x18\x04 \x01(\x02\"\xd8\x02\n\rFloatFunction\x12\x35\n\x0b\x63onst_value\x18\x01 \x01(\x0b\x32\x1e.ConstValueFloatFunctionConfigH\x00\x12,\n\x06linear\x18\x02 \x01(\x0b\x32\x1a.LinearFloatFunctionConfigH\x00\x12&\n\x03sin\x18\x03 \x01(\x0b\x32\x17.SinFloatFunctionConfigH\x00\x12*\n\x05steps\x18\x04 \x01(\x0b\x32\x19.StepsFloatFunctionConfigH\x00\x12,\n\x06repeat\x18\x05 \x01(\x0b\x32\x1a.RepeatFloatFunctionConfigH\x00\x12(\n\x04half\x18\x06 \x01(\x0b\x32\x18.HalfFloatFunctionConfigH\x00\x12*\n\x05\x63omb2\x18\x07 \x01(\x0b\x32\x19.Comb2FloatFunctionConfigH\x00\x42\n\n\x08\x66unctionb\x06proto3')



_CONSTVALUEFLOATFUNCTIONCONFIG = DESCRIPTOR.message_types_by_name['ConstValueFloatFunctionConfig']
_LINEARFLOATFUNCTIONCONFIG = DESCRIPTOR.message_types_by_name['LinearFloatFunctionConfig']
_SINFLOATFUNCTIONCONFIG = DESCRIPTOR.message_types_by_name['SinFloatFunctionConfig']
_STEPSFLOATFUNCTIONCONFIG = DESCRIPTOR.message_types_by_name['StepsFloatFunctionConfig']
_REPEATFLOATFUNCTIONCONFIG = DESCRIPTOR.message_types_by_name['RepeatFloatFunctionConfig']
_HALFFLOATFUNCTIONCONFIG = DESCRIPTOR.message_types_by_name['HalfFloatFunctionConfig']
_COMB2FLOATFUNCTIONCONFIG = DESCRIPTOR.message_types_by_name['Comb2FloatFunctionConfig']
_FLOATFUNCTION = DESCRIPTOR.message_types_by_name['FloatFunction']
ConstValueFloatFunctionConfig = _reflection.GeneratedProtocolMessageType('ConstValueFloatFunctionConfig', (_message.Message,), {
  'DESCRIPTOR' : _CONSTVALUEFLOATFUNCTIONCONFIG,
  '__module__' : 'functions_pb2'
  # @@protoc_insertion_point(class_scope:ConstValueFloatFunctionConfig)
  })
_sym_db.RegisterMessage(ConstValueFloatFunctionConfig)

LinearFloatFunctionConfig = _reflection.GeneratedProtocolMessageType('LinearFloatFunctionConfig', (_message.Message,), {
  'DESCRIPTOR' : _LINEARFLOATFUNCTIONCONFIG,
  '__module__' : 'functions_pb2'
  # @@protoc_insertion_point(class_scope:LinearFloatFunctionConfig)
  })
_sym_db.RegisterMessage(LinearFloatFunctionConfig)

SinFloatFunctionConfig = _reflection.GeneratedProtocolMessageType('SinFloatFunctionConfig', (_message.Message,), {
  'DESCRIPTOR' : _SINFLOATFUNCTIONCONFIG,
  '__module__' : 'functions_pb2'
  # @@protoc_insertion_point(class_scope:SinFloatFunctionConfig)
  })
_sym_db.RegisterMessage(SinFloatFunctionConfig)

StepsFloatFunctionConfig = _reflection.GeneratedProtocolMessageType('StepsFloatFunctionConfig', (_message.Message,), {
  'DESCRIPTOR' : _STEPSFLOATFUNCTIONCONFIG,
  '__module__' : 'functions_pb2'
  # @@protoc_insertion_point(class_scope:StepsFloatFunctionConfig)
  })
_sym_db.RegisterMessage(StepsFloatFunctionConfig)

RepeatFloatFunctionConfig = _reflection.GeneratedProtocolMessageType('RepeatFloatFunctionConfig', (_message.Message,), {
  'DESCRIPTOR' : _REPEATFLOATFUNCTIONCONFIG,
  '__module__' : 'functions_pb2'
  # @@protoc_insertion_point(class_scope:RepeatFloatFunctionConfig)
  })
_sym_db.RegisterMessage(RepeatFloatFunctionConfig)

HalfFloatFunctionConfig = _reflection.GeneratedProtocolMessageType('HalfFloatFunctionConfig', (_message.Message,), {
  'DESCRIPTOR' : _HALFFLOATFUNCTIONCONFIG,
  '__module__' : 'functions_pb2'
  # @@protoc_insertion_point(class_scope:HalfFloatFunctionConfig)
  })
_sym_db.RegisterMessage(HalfFloatFunctionConfig)

Comb2FloatFunctionConfig = _reflection.GeneratedProtocolMessageType('Comb2FloatFunctionConfig', (_message.Message,), {
  'DESCRIPTOR' : _COMB2FLOATFUNCTIONCONFIG,
  '__module__' : 'functions_pb2'
  # @@protoc_insertion_point(class_scope:Comb2FloatFunctionConfig)
  })
_sym_db.RegisterMessage(Comb2FloatFunctionConfig)

FloatFunction = _reflection.GeneratedProtocolMessageType('FloatFunction', (_message.Message,), {
  'DESCRIPTOR' : _FLOATFUNCTION,
  '__module__' : 'functions_pb2'
  # @@protoc_insertion_point(class_scope:FloatFunction)
  })
_sym_db.RegisterMessage(FloatFunction)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONSTVALUEFLOATFUNCTIONCONFIG._serialized_start=19
  _CONSTVALUEFLOATFUNCTIONCONFIG._serialized_end=65
  _LINEARFLOATFUNCTIONCONFIG._serialized_start=67
  _LINEARFLOATFUNCTIONCONFIG._serialized_end=122
  _SINFLOATFUNCTIONCONFIG._serialized_start=124
  _SINFLOATFUNCTIONCONFIG._serialized_end=206
  _STEPSFLOATFUNCTIONCONFIG._serialized_start=208
  _STEPSFLOATFUNCTIONCONFIG._serialized_end=302
  _REPEATFLOATFUNCTIONCONFIG._serialized_start=304
  _REPEATFLOATFUNCTIONCONFIG._serialized_end=392
  _HALFFLOATFUNCTIONCONFIG._serialized_start=394
  _HALFFLOATFUNCTIONCONFIG._serialized_end=475
  _COMB2FLOATFUNCTIONCONFIG._serialized_start=477
  _COMB2FLOATFUNCTIONCONFIG._serialized_end=593
  _FLOATFUNCTION._serialized_start=596
  _FLOATFUNCTION._serialized_end=940
# @@protoc_insertion_point(module_scope)
